Handle flatpak+https scheme
elementary/sideload pull request #170
Opened 2024-07-29 10:31 UTC by meisenzahl

Closes https://github.com/elementary/sideload/issues/169

2024-07-29 10:34 UTC, meisenzahl commented
I use [GLib.File.copy](https://valadoc.org/gio-2.0/GLib.File.copy.html) to download the FlatpakRef. This was the easiest way without adding new external dependencies.

2024-07-29 20:52 UTC, danirabbit requested changes
Works as expected, just one request to make sure we throw an error dialog or I can't remember if Sideload has an error view. Something that the user can see the error

2024-07-29 20:52 UTC, danirabbit commented on src/Application.vala
> +                critical ("Failed to download file from %s: %s", uri, e.message);
I think we probably need to throw an error that the user can see in case of a failure here

2024-07-30 10:58 UTC, meisenzahl commented
In order to be able to display an error to a user in the `ErrorView`, I unfortunately had to move the logic for parsing the Flatpak file to the `MainWindow`. @danirabbit let me know what you think.

2024-07-31 18:44 UTC, danirabbit approved these changes
Hey nice. I didn't realize that so many of these other errors were silent as well. Thanks for fixing those! Seems like everything is working as expected. Good job!

2024-07-31 18:44 UTC, merged